apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gprxy

resources:
- namespace.yaml
- serviceaccount.yaml
- secret.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- hpa.yaml

commonLabels:
  app: gprxy
  managed-by: kustomize

images:
- name: your-registry/gprxy
  newName: your-registry/gprxy
  newTag: latest
