apiVersion: v1
kind: ServiceAccount
metadata:
  name: gprxy
  namespace: gprxy
  labels:
    app: gprxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gprxy
  namespace: gprxy
rules:
- apiGroups: [ "" ]
  resources: [ "secrets", "configmaps" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gprxy
  namespace: gprxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gprxy
subjects:
- kind: ServiceAccount
  name: gprxy
  namespace: gprxy
