apiVersion: v1
kind: Service
metadata:
  name: gprxy
  namespace: gprxy
  labels:
    app: gprxy
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: gprxy
  ports:
  - name: postgres
    port: 7777
    targetPort: 7777
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
