apiVersion: v1
kind: Service
metadata:
  name: gprxy
  namespace: gprxy
  labels:
    app: gprxy
spec:
  type: ClusterIP
  selector:
    app: gprxy
  ports:
  - name: postgres
    port: 7777
    targetPort: 7777
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
